language: node_js

node_js: 
  - "10"

dist: trusty

install:

before_script:
  - npm audit --json >> /home/itadmin/Desktop/testingWebhook/report.json || true

script:
  - npm run audit:process























# name: Merge

# on: [pull_request]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     if: |
#         !(
#           (github.event.action == 'opened' || github.event.action == 'reopened')
#           && !github.event.pull_request.merged
#           && github.event.pull_request.merge_commit_sha != null
#         )

#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

#     steps:
#     - uses: actions/checkout@v1
#     - name: Check merge commit of Pull Request
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: npm audit
#       run: |
#         npm audit
#       env:
#         CI: true
