name: merge

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: |
        !(
          (github.event.action == 'opened')
          && !github.event.pull_request.merged
          && github.event.pull_request.merge_commit_sha != null
        )

    - name: npm audit
      run: |
        npm audit --json >> /home/itadmin/Desktop/testingWebhook/report.json || true