name: Merge
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm install, and test
      run: |
        npm audit --json >> /home/itadmin/Desktop/testingWebhook/report.json || true

























# name: Test on Pull Request
# on: [pull_request]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: |
#         !(
#           (github.event.action == 'opened' || github.event.action == 'reopened')
#           && !github.event.pull_request.merged
#           && github.event.pull_request.merge_commit_sha != null
#         )
#     steps:
#       - name: Check merge commit of Pull Request
#         with: 
#           ref: ${{ github.event.pull_request.merge_commit_sha }}
#       - name: Test Hook
#         run: npm audit